version: '2'

services:
    jenkins:
        image: jenkins:1.651.2
        container_name: jenkins
        links:
        - xldeploy:xldeploy
        - gogs:gogs
        ports:
        - 8080:8080

    xldeploy:
        build: docker-xldeploy/.
        container_name: xldeploy
        ports:
        - 4516:4516
    gogs:
        build: docker-gogs/.
        container_name: gogs
        ports:
        - 3000:3000
    git:
        build: docker-git/.
        container_name: git
